package net.runelite.client.plugins.AutoRogues;

public enum State {
    BANKIN,
    CHILLIN,
    TIMEOUT,
    ENTER_DEN,
    RUNNIN,
    OBSTACLE_1, OBSTACLE_2, OBSTACLE_3, OBSTACLE_4, OBSTACLE_5, OBSTACLE_6, OBSTACLE_7, OBSTACLE_8, OBSTACLE_9, OBSTACLE_10, OBSTACLE_11, OBSTACLE_12_HIGH, OBSTACLE_12_LOW, OBSTACLE_13_LOW, OBSTACLE_14_LOW, OBSTACLE_15_LOW, OBSTACLE_16_LOW, OBSTACLE_17_LOW, OBSTACLE_18_LOW, OBSTACLE_19_LOW, OBSTACLE_20_LOW, OBSTACLE_21_LOW, OBSTACLE_22_LOW, OBSTACLE_23_LOW, OBSTACLE_24_LOW, OBSTACLE_25_LOW, OBSTACLE_26_LOW, OBSTACLE_27_LOW, OBSTACLE_28_LOW, OBSTACLE_29_LOW, OBSTACLE_30_LOW, OBSTACLE_31_LOW, OBSTACLE_32_LOW, OBSTACLE_33_LOW, OBSTACLE_34_LOW, OBSTACLE_35_LOW, OBSTACLE_36_LOW, OBSTACLE_37_LOW, OBSTACLE_38_LOW, OBSTACLE_39_LOW, OBSTACLE_40_LOW, OBSTACLE_41_LOW, OBSTACLE_42_LOW, OBSTACLE_43_LOW, OBSTACLE_44_LOW, OBSTACLE_45_LOW, OBSTACLE_46_LOW, OBSTACLE_13_HIGH, OBSTACLE_14_HIGH
}
